### ISSUE TITLE
Parsing insert queries with functions trims commas

### ISSUE THREAD

**Issue by gachowy** [phpmyadmin/sql-parser#450]
Hello,

I discovered that there could be something wrong with parsing commas in MySQL functions like `concat` or `replace`. 

When I'm trying to parse, and fetch values, or rebuild INSERT queries, which contains some concat, or replace, it 'eats' all commas, which makes output queries as invalid.

Sample parsed queries:
```sql
INSERT INTO `some_table` VALUES (replace('something_camel_case','_', ''));
INSERT INTO `some_table` VALUES (concat('value1', 'value2', 'value3'));
```

Output queries:
```sql
INSERT INTO `some_table` VALUES (replace('something_camel_case''_' ''));
INSERT INTO `some_table` VALUES (concat('value1' 'value2' 'value3'));
```

**Version:** 5.7.0
**PHP:** 8.2.6

**Code example:**
```php
<?php

use PhpMyAdmin\SqlParser\Parser;
use PhpMyAdmin\SqlParser\Statements\InsertStatement;

require_once __DIR__ . '/vendor/autoload.php';

$inputQueries = "
INSERT INTO `some_table` VALUES (replace('something_camel_case','_', ''));
INSERT INTO `some_table` VALUES (concat('value1', 'value2', 'value3'));
";

$parser = new Parser($inputQueries);

foreach ($parser->statements as $statement) {
    if ($statement instanceof InsertStatement) {
        var_dump($statement->values[0]->raw[0]);
    }
    var_dump($statement->build());
}
```

**Comment by williamdes** [comment]
Is 5.8.0 (aka 5.8.x branch) also affected?
Please about #452 and other ones, if possible send them to the QA branch: 5.latest.x
I will do it for #452 in order to have the phpdoc fixed in 5.8

**Comment by gachowy** [comment]
@williamdes seems like newer/dev versions also affected - still the same issue :)

**Comment by williamdes** [comment]
Okay, let's try to fix it before #449 
Are you using sql-parser for a project ?

**Comment by Tithugues** [comment]
Here is a proposal for a fix: https://github.com/phpmyadmin/sql-parser/pull/474

**Comment by williamdes** [comment]
Hi @gachowy
Can you confirm 5.8 fixes the issue for you?

**Comment by gachowy** [comment]
Hello, @williamdes - it seems fixed in 5.8. 
Thanks :)
